### ISSUE TITLE
Document Install Procedure, or add to registry?

### ISSUE THREAD

**Issue by grempe** [types/npm-big-integer#1]
Hello,

I'm pretty new to TypeScript and i was trying to use the definitions I found here:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/big-integer/big-integer.d.ts

These though don't seem to define `modPow`.  I thought I would try yours, from this repository, but I'm not sure how to go about installing using the current version of typings.

Could you please add to the readme some instructions for installation?  Or is it possible to add this to the typings registry (or whichever is appropriate) so installation is easier?

I'll file a bug on the other for `modPow`.

Thanks.

**Comment by demurgos** [comment]
Oh, sorry for the long time to answer:
This project is part of [`typings`](https://github.com/typings/typings), a replacement for TSD (mainly to solve global declarations and correctly mimic the way Node works and also add support for multiple sources).

I'll add a note in the `README.md` about it to make it clearer.

To install it, you will need:

``` bash
npm install -g typings
typings install --save big-integer
# install the definition to typings/modules/big-integer/index.d.ts
```

I do not remember exactly, but there is also a command to convert a `tsd` config file to a `typings` config. (something like `typings upgrade` but you should check the link above)

**Comment by demurgos** [comment]
I believe that you managed to install the type definitions. I'll close the issue.
