### ISSUE TITLE
Enable Travis CI

### ISSUE THREAD

**Issue by demurgos** [types/npm-big-integer#3]
@unional @felixfbecker @blakeembrey 

Could one of you enable Travis CI for this repo ? I have the rights to enable it when I create a repo, but here I transferred the ownership from `demurgos/npm-big-integer` to `types/big-integer` and do not have the rights.

**Comment by unional** [comment]
Done. 🌷

**Comment by demurgos** [comment]
Thank you 👍 

Could you maybe take a look at #4 ? It might be longer than enabling Travis, but you seem to be the one who implemented browser tests for the Yeoman generator.
