### ISSUE TITLE
Perform browser tests

### ISSUE THREAD

**Issue by demurgos** [types/npm-big-integer#4]
Hi,
I tried to implement browser tests with JSPM but couldn't manage to configure it.

I tried to use the Yeoman generator or use the code from other repos but I do not understand exactly how the tests are run. I think that I was able to compile the files and start a server, but then it errored with a TypeError (`substr` is not defined on `undefined`).

For the moment, I am only running the server tests.

**Comment by unional** [comment]
Is there a reason to do browser test for this?
I can't find any browser specific behavior for https://github.com/peterolson/BigInteger.js

**Comment by demurgos** [comment]
Effectively, there is no browser-specific behavior but one of the questions of the generator is about the environment. I answered that this library can be used in the browser so it tried to create tests for the browser.

Even if it should output the same result as the server tests, I hoped to see how it is implemented with this relatively simple library so then I'll be able to implement it myself for other libraries without bothering you.

If you think that the server tests are enough for this library, we can leave it this way (with only the server tests, I'll also add the source tests).

**Comment by unional** [comment]
I see.
I would write browser test only if the library is intended to be run on browser only or if there are any browser specific behavior (for example: [`aurelia-logging-color`](https://github.com/unional/aurelia-logging-color)).

How to run browser test depends on which test framework you use.
With `blue-tape` and many others, you will probably use `karma-*` and pair with `phantomJS` or `electron` to make it headless.

If you are into `jspm`, you can take a look at https://github.com/unional/karma-systemjs-sample
It's a bit old so things may have changed a bit.

Personally I'm using `ava` now and also finding ways to run browser test as smooth as possible.
`karma-ava` is not ready and I'm using `browser-env`/`jsdomify` but I'm running into a corner case that I working right now (literally, as I'm typing this. 😛 ).

**Comment by demurgos** [comment]
Ok, thanks for information and links to examples. 🙂 

I was using `jspm` with the typescript plugin and blue-tape/electron. It's the first time I hear about Ava: I checked its page and it looks good, I might give it a try for a personal project.

> I would write browser test only if the library is intended to be run on browser only or if there are any browser specific behavior

Ok, so I'll close this issue for the moment.
